var ALIASES = {};
ALIASES["hamming"] = {};
ALIASES["ieee754"] = {};
ALIASES["libc"] = {};
ALIASES["num_integer"] = {};
ALIASES["num_traits"] = {};
ALIASES["ramp"] = {};
ALIASES["rand"] = {};
ALIASES["rand_core"] = {};
